import type { Metadata } from "next";
import localFont from "next/font/local";
import { Provider } from "@/components/ui/provider";
import { Container, Box, Image } from "@chakra-ui/react";
import Navbar from "@/components/ui/navbar";
import Hero from "@/components/page/root/hero";
import Cards from "@/components/page/root/cards";
import Footer from "@/components/page/root/footer";

const inter = localFont({
  src: "./fonts/Inter-VariableFont_opsz,wght.ttf",
});

export const metadata: Metadata = {
  title: "LearnLimit - Home",
  description: "Learn Limit Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter} antialiased`}>
        <Provider>
          <Box maxW={"dvw"} overflow={"hidden"}>
            <Navbar />
            <Container
              fluid={true}
              minH="dvh"
              w={"dvw"}
              px="2"
              centerContent={false}
              bgColor={"white"}
              color={"black"}
              py="4"
            >
              {children}
            </Container>
            <Footer />
          </Box>
        </Provider>
      </body>
    </html>
  );
}
